#!/usr/bin/env bash
# 生成 deploy/.env：随机 PostgreSQL / Redis 密码与应用连接串（勿提交 .env）
# 已存在 .env 时默认跳过，避免覆盖线上密码；强制重写：FORCE_REGENERATE=1 ./generate-env.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="${ROOT}/.env"

if [[ -f "${OUT}" && -z "${FORCE_REGENERATE:-}" ]]; then
  echo "${OUT} already exists; skipping (set FORCE_REGENERATE=1 to overwrite)."
  exit 0
fi

rand_alnum() {
  openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c "${1:?length}"
}

POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_DB="${POSTGRES_DB:-all_in_ai}"
POSTGRES_PASSWORD="$(rand_alnum 32)"
REDIS_PASSWORD="$(rand_alnum 32)"
ADMIN_PASSWORD="$(rand_alnum 20)"

APP_ENV="${APP_ENV:-production}"
DEBUG="${DEBUG:-false}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"
HTTP_PORT="${HTTP_PORT:-80}"
API_IMAGE_NAME="${API_IMAGE_NAME:-ai-assistant-api}"
API_IMAGE_TAG="${API_IMAGE_TAG:-latest}"

ASYNC_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
SYNC_URL="postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379/0"

umask 077
cat > "${OUT}" << EOF
# Generated by deploy/generate-env.sh — keep secret, do not commit
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

REDIS_PASSWORD=${REDIS_PASSWORD}

DATABASE_URL=${ASYNC_URL}
DATABASE_SYNC_URL=${SYNC_URL}
REDIS_URL=${REDIS_URL}

APP_ENV=${APP_ENV}
DEBUG=${DEBUG}
LOG_LEVEL=${LOG_LEVEL}

ADMIN_PASSWORD=${ADMIN_PASSWORD}

HTTP_PORT=${HTTP_PORT}
API_IMAGE_NAME=${API_IMAGE_NAME}
API_IMAGE_TAG=${API_IMAGE_TAG}
EOF

chmod 600 "${OUT}" 2>/dev/null || true
echo "Wrote ${OUT}"
echo "Default admin user (first init only): admin / password in ADMIN_PASSWORD above."
echo "Start stack: cd ${ROOT} && docker compose up -d --build"
